name: Cypress Tests

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["master"]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v5 # use the explicit version number
        # with:
        #   build: npm run build
        #   start: npm start