name: Unit test
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
          node-version: "19.5"
    # Install required deps for action
    - name: Install Dependencies
      run: npm install
    # Finally, run our tests and collect coverage
    - name: Run the tests
      run: npm test --coverage
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v1
      with:
        token: 2a961002-7363-486a-a553-54281d768bfa
